# Generated by Django 3.2.1 on 2021-05-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210527_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20)),
                ('message', models.TextField()),
                ('subject', models.TextField(default='SOME STRING')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
